language: node_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md$)|(.json$)'
      then
        echo "Docs update or merge, skipping build"
        exit
      fi
install:
  - npm i
script:
  - npm test
  - npm run go
# - npx deploy # TODO add this step soon
