language: node_js
node_js:
  - "10.15"
branches:
  only:
  - master
before_install:
  - |
      if ! git log -1 --stat --format="%s %b" | grep -qvE '(Lambda shell commands update:)'
      then
        echo "Docs update or merge, skipping build"
        exit
      fi
install:
  - npm i
script:
  - npm test
  - npm run go
# - npx deploy # TODO add this step soon
